[workspace]
resolver = "3"
members = ["libm-ext", "."]

[workspace.package]
authors = ["tangxiangong <tangxiangong@gmail.com>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/tangxiangong/libm-ext"
version = "0.1.0"
edition = "2024"

[package]
name = "libm-ext-py"
authors.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true
edition.workspace = true

[lib]
name = "_core"
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "stub_gen"
path = "src/bin/stub_gen.rs"
required-features = ["stub-gen"]

[features]
stub-gen = ["pyo3-stub-gen"]

[dependencies]
pyo3 = { version = "0.27", features = ["abi3-py311"] }
pyo3-stub-gen = { version = "0.17", optional = true }
