[package]
name = "libm-ext-py"
authors = ["tangxiangong <tangxiangong@gmail.com>"]
license = "MIT OR Apache-2.0"
version = "0.0.2"
edition = "2024"

[lib]
name = "_core"
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "stub_gen"
path = "src/bin/stub_gen.rs"
required-features = ["stub_gen"]

[features]
stub_gen = ["pyo3-stub-gen"]

[dependencies]
libm-ext = { path = "libm-ext" }
num_cpus = "1"
numpy = "0.27"
paste = "1.0"
pyo3 = { version = "0.27", features = ["abi3-py311"] }
pyo3-stub-gen = { version = "0.17", optional = true }
rayon = "1.11"
