# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401

import builtins
import numpy
import numpy.typing

def cospi(x: builtins.float) -> builtins.float:
    r"""
    Compute $\cos(\pi x)$ more accurately than `cos(pi*x)`, especially for large `x` (f64).
    """

def cospi_vectorized_parallel(v: numpy.typing.NDArray[numpy.float64]) -> numpy.typing.NDArray[numpy.float64]: ...

def cospi_vectorized_serial(v: numpy.typing.NDArray[numpy.float64]) -> numpy.typing.NDArray[numpy.float64]: ...

def cospif(x: builtins.float) -> builtins.float:
    r"""
    Compute $\cos(\pi x)$ more accurately than `cos(pi*x)`, especially for large `x` (f32).
    """

def cospif_vectorized_parallel(v: numpy.typing.NDArray[numpy.float32]) -> numpy.typing.NDArray[numpy.float32]: ...

def cospif_vectorized_serial(v: numpy.typing.NDArray[numpy.float32]) -> numpy.typing.NDArray[numpy.float32]: ...

def sincospi(x: builtins.float) -> tuple[builtins.float, builtins.float]:
    r"""
    Simultaneously compute [`sinpi`] and [`cospi`] (f64).
    """

def sincospif(x: builtins.float) -> tuple[builtins.float, builtins.float]:
    r"""
    Simultaneously compute [`sinpif`] and [`cospif`] (f32).
    """

def sinpi(x: builtins.float) -> builtins.float:
    r"""
    Compute $\sin(\pi x)$ more accurately than `sin(pi*x)`, especially for large `x` (f64).
    """

def sinpi_vectorized_parallel(v: numpy.typing.NDArray[numpy.float64]) -> numpy.typing.NDArray[numpy.float64]: ...

def sinpi_vectorized_serial(v: numpy.typing.NDArray[numpy.float64]) -> numpy.typing.NDArray[numpy.float64]: ...

def sinpif(x: builtins.float) -> builtins.float:
    r"""
    Compute $\sin(\pi x)$ more accurately than `sin(pi*x)`, especially for large `x` (f32).
    """

def sinpif_vectorized_parallel(v: numpy.typing.NDArray[numpy.float32]) -> numpy.typing.NDArray[numpy.float32]: ...

def sinpif_vectorized_serial(v: numpy.typing.NDArray[numpy.float32]) -> numpy.typing.NDArray[numpy.float32]: ...

